# Generated by Django 6.0.1 on 2026-04-10 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('category', models.CharField(choices=[('Personal', 'Personal'), ('Professional', 'Professional')], max_length=20)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('easypaisa', 'Easypaisa'), ('jazzcash', 'JazzCash')], max_length=20)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('where_spent', models.CharField(max_length=255)),
            ],
        ),
    ]
