# Generated by Django 6.0.1 on 2026-06-01 19:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ROSCAGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('total_payout', models.DecimalField(decimal_places=2, help_text='Total prize pool paid to the monthly winner.', max_digits=12, validators=[django.core.validators.MinValueValidator(1)])),
                ('monthly_contribution', models.DecimalField(decimal_places=2, help_text='Fixed amount each member pays every month.', max_digits=12, validators=[django.core.validators.MinValueValidator(1)])),
                ('duration_months', models.PositiveIntegerField(help_text='Total cycle length in months.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ROSCA Group',
                'verbose_name_plural': 'ROSCA Groups',
                'ordering': ['-is_active', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number must be 11 digits starting with 03 (e.g. 03001234567).', regex='^03[0-9]{9}$')])),
                ('cnic', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='CNIC must be in the format 12345-1234567-1.', regex='^[0-9]{5}-[0-9]{7}-[0-9]{1}$')])),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rosca_participations', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='rosca.roscagroup')),
            ],
            options={
                'ordering': ['-joined_at'],
            },
        ),
        migrations.CreateModel(
            name='DrawWinner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('year', models.PositiveIntegerField()),
                ('prize_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('drawn_at', models.DateTimeField(auto_now_add=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draw_wins', to='rosca.participant')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draw_winners', to='rosca.roscagroup')),
            ],
            options={
                'ordering': ['-year', '-month', '-drawn_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('year', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('transaction_id', models.CharField(editable=False, max_length=32, unique=True)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='rosca.participant')),
            ],
            options={
                'ordering': ['-year', '-month', '-paid_at'],
                'constraints': [models.UniqueConstraint(fields=('participant', 'month', 'year'), name='unique_payment_per_participant_month')],
            },
        ),
        migrations.AddConstraint(
            model_name='participant',
            constraint=models.UniqueConstraint(fields=('user', 'group'), name='unique_user_per_rosca_group'),
        ),
        migrations.AddConstraint(
            model_name='participant',
            constraint=models.UniqueConstraint(fields=('group', 'cnic'), name='unique_cnic_per_rosca_group'),
        ),
        migrations.AddConstraint(
            model_name='drawwinner',
            constraint=models.UniqueConstraint(fields=('group', 'month', 'year'), name='unique_draw_per_group_month'),
        ),
    ]
