# Generated by Django 6.0.1 on 2026-06-01 19:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rosca', '0002_sample_pools'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='cnic',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='CNIC must be exactly 13 digits.', regex='^[0-9]{5}-[0-9]{7}-[0-9]{1}$')]),
        ),
    ]
